### PR TITLE
Go to PWA!

### PR DESCRIPTION
**Pull request by DivadNojnarg**
- tell golem how to load the manifest.json
- fix wrong path in manifest.json (icons) and start url

Also make sure to reinstall the latest level shinyMobile version

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
This is not a permanent fix. shinyMobile will support this later

**Comment by JohnCoene** [comment]
Thank you, let me merge and try this.

**Comment by JohnCoene** [comment]
I had tried something like that before it did not work. It still does not on my iPhone. I have restarted the shiny server and cleared cache. Google Chrome correctly finds the manifest.json but the icons are not used for add to home screen.

**Comment by DivadNojnarg** [comment]
Do you have android or iOS?

**Comment by JohnCoene** [comment]
iOS

**Comment by DivadNojnarg** [comment]
Well. In that cas you need to manually add: shiny::tags$link(rel = "apple-touch-icon", href = "www/icons/apple-touch-icon.png"), and also create the corresponding icon.

**Comment by JohnCoene** [comment]
Don't know why it took me so long to try this. Works perfectly fine, thanks!

**Pull request merged**
